language: php
php:
- 7.2
env:
  global:
    - secure: "UENxQUgUm0buyugewFTILloQb157RugVp29W7DmhW3pBorYqF+qwJTr0o/pNmDd7yeVueiHYffavHbMgPuZ/M1oYKhQGJxtdCNMZsG3lhe6ylgvx4I9xCpCBXF9LKUxTkEPAJFIXT96b8b5q2Ql0mGQXQnCTnDgRfvXZUZnZGHn3GZR4jqzw1OOWdhosZzShvDeokt0AeJEiI7CPpAxhjmrzsLRKaTAtfYuTvjX7xNEYBLfWhDNqbTxH5MmwIvGU1p+acuNhRZAXx8Kf5HXfEPO0USXptNPVoV00V6OZaY+TUVIVMoXgr92m7FFeo7Ii0du8Ar71Zu2uNJJEODOy2UKyU/LLAL3aHLB0mSs2ZO/MTI4ZAVWEQosLHWdKu4QYhhm41tA80jyR4hZLYxGJatPBHFEm4JqpXPBuooAgk9GrPDrUf9F6hWTtORyBZGwbIV3GEUhvcKztVBzwAKxTfy6tQwY3R4qdwy9fjvgIGBF+yNTlNMujmoBpzaXxYoDBAjt6m8tv5SyWquN+QuMvyeF0THsoNFpdC/PzztVMmOFTc/tT5Zz5cuYn+idiM0+/+a2QLTj88Nbc2STd1I1YIVX0QgaDbcHjHwl+2+4FtRvhyI3JuNlN5QN+y8TgIF/Uz/EBiCjcLYhlpK09dAlzb+A1Fx0dEFJypeduKVTF9Zw="
    - secure: "IzYm/lE5Q4X6MBzFOGmuZQ66a9O/pRtP1ERbGnzFy/F9PJUCeTOIEV1dAR0R9mLWaosl+dT4xVNWSfNcZ2ViPn+OKAkADOGfKzKJEowqXXBG5qxdoiUG+rwwUqS0LPs3zYeShYooUO5or0ac9toF7vylREu1HWO7jb/2ZhI0cM1viKW0cN1K+Qbzz0r3Ys62qNIg8RTKp96AvXWb6BepImx5WU6QPEDsMf1mCH3ajZ5CFRo7rRpmLswllEiLXHPk55b2iq+V2OsymB6ddVlnehKbPpcYftGOjg5dzrYRWVIQwQcKFitzCCGXqEmCkgm8MZ6Vp10BfENX0PzK4SvBFe3R4EnSRURupCKnspQAaCK0lhdeBJUCimh3yM5ofqVmstffKsHhWSRCgt+xfjsYjKSrpJdA49wWUwbECHsql2LhUvV7i7vyb/lMyj1TsGEq+ChdKhMitv/Ex+sJy28Up/GGG3m7vKOMc6Aum7QFZBkQxdE84iGChusAIWLZnRE0lk8STRpd5xBvcj2iE6aG0EezSvBasBRiJW3d7gjWozfta3Jvhw089ElIFd7/f1yo7qTFk/Hj6QkpFfWCLlHvrSb0mTZ/DFVD1UtamLnPUybsF5xf+5497GIGg5AwOC6zrO5p62kFcnuI9oFHLFVzAEQ3ijfqPGzlD5OHTcYY5jw="
script:
- php run.php
#notifications:
#  email:
#    recipients:
#    - support@redux.io
#    on_failure: always
